# -*- coding: utf-8 -*-
"""Supermercado-CasaRica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15NHH6mcA3Up_gu8JXmb2bkFOiiGw0xEJ

Supermercado - CASA RICA
"""

#Importar las librerias
import pandas as pd
from bs4 import BeautifulSoup
import requests

#Definir número de paginas
no_pages = 2

#Funcion para obtener los datos de las páginas
def get_data(pageNo):  
    headers = {
    'authority': 'www.casarica.com.py',
    'pragma': 'no-cache',
    'cache-control': 'no-cache',
    'dnt': '1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'sec-fetch-site': 'none',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-dest': 'document',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
    }
    r = requests.get('https://www.casarica.com.py/productos?q=cafe&post_type=product'+str(pageNo)+'?ie=UTF8&pg='+str(pageNo), headers=headers)
    content = r.content
    soup = BeautifulSoup(content)
    #print(soup)

    alls = []
    for d in soup.findAll('div', attrs={'class':'product'}):
        #print(d)
        name = d.find('h2', attrs={'class':'ecommercepro-loop-product__title'})
        #print(n[0]['alt'])
        #date= d.find('span', attrs={'class':'a-text-bold'})
        price = d.find('span', attrs={'class':'price'})
        oferta= d.find('span', attrs={'class':'ecommercepro-Price-currencySymbol'})

        all1=[]

        if name is not None:
            #print(n[0]['alt'])
            all1.append(name.text)
        else:
            all1.append('0')     

        if price is not None:
            #print(price.text)
            all1.append(price.text)
        else:
            all1.append('0')

        if oferta is not None:
            #print(oferta.text)
            all1.append(oferta.text)
        else:
            all1.append('No tiene ofertas')
        alls.append(all1)    
    return alls

#Listar y ordenar los datos en un df
#Agregar columnas necesarias
#Descargar el archivo en formato .csv
results = []
for i in range(1, no_pages+1):
    results.append(get_data(i))
flatten = lambda l: [item for sublist in l for item in sublist]
df = pd.DataFrame(flatten(results),columns=['Name', 'Price', 'Oferta'])
df.to_csv('casarica_products.csv', index=False, encoding='utf-8')

#Realizar la impresion de los datos obtenidos
df

"""

```
# Este código esta basado en el código de Alejandra Chavez, Msc.
```

"""